#!/bin/sh

context=$(cd "${0%/*}"; pwd -P)

log() {
   echo "$@" >&2
}

log "-----"
log "context: $context"
log "@: $@"
log "__target_user: $__target_user"
log "__target_host: $__target_host"

# prefix destination with host
source="$1"
destination="${__target_host}:${2}"
set -x
exec scp -o User=$__target_user -q "$source" "$destination"
#cp --dereference "$source" "$destination"
