#!/bin/sh

: ${XDG_RUNTIME_DIR:="$(d="/tmp/xdg-runtime-$USER"; umask 077 && mkdir "$d" && echo "$d")"}

control_path_base_dir="$XDG_RUNTIME_DIR/cdist-ssh"
[ -d "$control_path_base_dir" ] || {
   echo "control_path_base_dir: $control_path_base_dir" | logger
   mkdir "$control_path_base_dir"
   chmod 700 "$control_path_base_dir"
}
control_path_dir="$control_path_base_dir/${__target_host##*+}"
[ -d "$control_path_dir" ] || {
   echo "control_path_dir: $control_path_dir" | logger
   mkdir "$control_path_dir"
}

exec ssh \
   -o User=$__target_user \
   -o ForwardX11=no \
   -o ControlMaster=auto \
   -o ControlPath="$control_path_dir/%r@%h:%p" \
   -o ControlPersist=60 \
   "$__target_host" "$@"

#echo "$@" | /bin/sh
