#!/bin/sh

: ${XDG_RUNTIME_DIR:="$(d="/tmp/xdg-runtime-$USER"; umask 077 && mkdir -p "$d" && echo "$d")"}

control_path_base_dir="$XDG_RUNTIME_DIR/cdist-ssh"
[ -d "$control_path_base_dir" ] || {
   echo "control_path_base_dir: $control_path_base_dir" | logger
   mkdir "$control_path_base_dir"
   chmod 700 "$control_path_base_dir"
}
target_host_id="$(echo "${__target_host##*+}" | cksum | awk '{print $1}')"
control_path_dir="$control_path_base_dir/${target_host_id}"
[ -d "$control_path_dir" ] || {
   echo "control_path_dir: $control_path_dir" | logger
   mkdir "$control_path_dir"
}

exec ssh \
   -o User=$__target_user \
   -o ForwardX11=no \
   -o ControlMaster=auto \
   -o ControlPath="$control_path_dir/%r@%h:%p" \
   -o ControlPersist=10 \
   "$__target_host" "$@"

#echo "$@" | /bin/sh
