#!/bin/sh

context=$(cd "${0%/*}"; pwd -P)
parent="${context}/.."

log() {
   echo "$@" >&2
}

log "-----"
log "context: $context"
log "parent: $parent"
log "@: $@"
log "__target_path: $__target_path"

# prefix destination with chroot
source="$1"
destination="${__target_path}${2}"
# pass the execution up the stack
set -x
exec "$parent/$mode" "$source" "$destination"
