#!/bin/sh

context=$(cd "${0%/*}"; pwd -P)
parent="${context}/.."

log() {
   echo "$@" >&2
}

log "-----"
log "context: $context"
log "parent: $parent"
log "@: $@"
log "__target_path: $__target_path"

# escape ' with '"'"'
code="$(echo "$@" | sed -e "s/'/'\"'\"'/g")"
# pass the execution up the stack
#set -x
exec "$parent/exec" "chroot $__target_path sh -c '$code'"
