#!/bin/sh

context=$(cd "${0%/*}"; pwd -P)
parent="${context}/.."

log() {
   echo "$@" >&2
}

log "-----"
log "context: $context"
log "parent: $parent"
log "@: $@"

source="$1"
destination="$2"
# pipe to parent exec to allow uploading as user
#set -x
exec cat "$source" | "$parent/exec" "sudo sh -c 'cat > \"$destination\"'"
